apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cluster-autoscaler
  namespace: kube-system
  annotations:
    meta.helm.sh/release-name: cluster-autoscaler-release
spec:
  interval: 2m0s
  chart:
    spec:
      chart: cluster-autoscaler
      version: 9.29.0
      sourceRef:
        kind: HelmRepository
        name: cluster-autoscaler
        namespace: kube-system
      interval: 10m0s
  valuesFrom:
    - kind: ConfigMap
      name: cluster-autoscaler-overrides
