apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - helm-repository.yaml

configMapGenerator:
  - name: cluster-autoscaler-overrides
    namespace: kube-system 
    files:
      - values.yaml
      
generatorOptions:
  disableNameSuffixHash: true

